databases:
  - name: spree-db
    databaseName: spree
    user: spree

services:
  - type: web
    name: spree-web
    runtime: ruby
    plan: standard
    buildCommand: bin/render-build.sh
    preDeployCommand: bin/rails db:migrate && bin/rails db:seed
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spree-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
  - type: worker
    name: spree-worker
    runtime: ruby
    plan: standard
    buildCommand: bin/render-build.sh
    startCommand: "bundle exec rake solid_queue:start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spree-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false