version: 2
jobs:
  install_ruby_dependencies:
    docker:
      - image: cimg/ruby:3.0.3-node
    working_directory: ~/app
    environment:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v4-{{ checksum "Gemfile.lock" }}
            - ruby-dependencies-v4
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Bundle Install
          command: |
            bundle check || bundle install --deployment
      - save_cache:
          paths:
            - vendor/bundle
          key: ruby-dependencies-v4-{{ checksum "Gemfile.lock" }}

  run_tests:
    docker:
      - image: cimg/ruby:3.0.3-node
      - image: postgres:13.0-alpine
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    parallelism: 2
    environment:
      RAILS_ENV: test
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v4-{{ checksum "Gemfile.lock" }}
            - ruby-dependencies-v4
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432
      - run:
          name: Bundle install
          command: bundle check || bundle install --deployment
      - run:
          name: Setup DB
          command: bundle exec rails db:create db:schema:load
      - run:
          name: Run Rspec
          command: |
            bundle exec rspec --format documentation \
                              --format RspecJunitFormatter \
                              -o ~/rspec/rspec.xml
      - store_test_results:
          path: ~/rspec

      - store_artifacts:
          path: tmp/capybara

workflows:
  version: 2
  main:
    jobs:
      - install_ruby_dependencies
      - run_tests:
          requires:
            - install_ruby_dependencies
