# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22d9b7aa31a1327bcc4b21e4638a25b0b13b3947a59f0009bda8f754bc95de606abe3f80242f1fb864984a71e1fc94c18a422b1094a223cd1defe3d4147bc995

  sidekiq_username: admin
  sidekiq_password: password

  flipper_username: admin
  flipper_password: password

  mailchimp_api_key: <%= ENV['MAILCHIMP_API_KEY'] %>
  mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
  mailchimp_segment_name: project-name

test:
  secret_key_base: b917aca59215615d618edaf2f02a20504f85f59dc61e04e3ae85431ab4a586049baef9b0e4265f65cd0d5a2556fdd2192adf1a51229182a1006d2dc78caa545c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  sidekiq_username: <%= ENV["SIDEKIQ_USERNAME"] %>
  sidekiq_password: <%= ENV["SIDEKIQ_PASSWORD"] %>

  flipper_username: <%= ENV["FLIPPER_USERNAME"] %>
  flipper_password: <%= ENV["FLIPPER_PASSWORD"] %>

  mailchimp_api_key: <%= ENV['MAILCHIMP_API_KEY'] %>
  mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
  mailchimp_segment_name: <%= ENV['MAILCHIMP_SEGMENT_NAME'] %>

  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
